def throwError(message):
     print(message)
     quit()